image: ghcr.io/fortheusers/sealeo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.common: &common
  script:
    - make $PLATFORM
  artifacts:
    paths:
      - appstore.$EXT

PC:
  <<: *common
  variables:
    PLATFORM: pc
    EXT: bin

WiiU:
  <<: *common
  variables:
    PLATFORM: wiiu
    EXT: wuhb

Switch:
  <<: *common
  variables:
    PLATFORM: switch
    EXT: nro
