name: Build console app

on:
  push:
    branches:
      - main
      - pc-builds-ci
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: wiiu
            ext: rpx
          - platform: wiiu
            ext: wuhb
          - platform: switch
            ext: nro
          - platform: 3ds
            ext: 3dsx
          - platform: wii
            ext: dol
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.platform }}
      run: make ${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
        name: appstore.${{ matrix.ext }}
        path: /__w/hb-appstore/hb-appstore/appstore.${{ matrix.ext }}