name: Build PC client apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        library: [sdl2, sdl1]
    runs-on: ${{ matrix.os }-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.platform }}
      run: /__w/hb-appstore/hb-appstore/libs/chesto/helpers/build_pc.sh ${{ matrix.os }} ${{ matrix.library }}}
    - uses: actions/upload-artifact@v3
      with:
        name: appstore-${{ matrix.ext }}
        path: /__w/hb-appstore/hb-appstore/appstore_${{ matrix.os }}}_${{ matrix.library }}}.zip